name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, bcmath, zip, pdo_pgsql, sqlite3, pdo_sqlite
          coverage: none
      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist
      - name: Prepare app (env, dirs, DB)
        run: |
          cp .env.example .env || true
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate --ansi
          mkdir -p storage/framework/{cache,sessions,views,testing} bootstrap/cache
          touch database/database.sqlite
          php artisan migrate --no-interaction --force
      - name: Run tests
        run: php artisan test --colors=always

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - name: Install PHP deps (for Ziggy)
        run: |
          composer install --no-interaction --no-progress --prefer-dist --no-dev
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install and build
        run: |
          if [ -f package.json ]; then npm ci && npm run build; else echo "No package.json yet"; fi
